"""First migration

Revision ID: c337e229d453
Revises: 
Create Date: 2025-01-05 18:00:20.544254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c337e229d453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('muzzle_speed', sa.Float(), nullable=False),
    sa.Column('vertical_angle', sa.Float(), nullable=False),
    sa.Column('horizontal_angle', sa.Float(), nullable=False),
    sa.Column('projectile_weight', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('final_position_lat', sa.Float(), nullable=False),
    sa.Column('final_position_lon', sa.Float(), nullable=False),
    sa.Column('final_position_alt', sa.Float(), nullable=False),
    sa.Column('horizontal_distance', sa.Float(), nullable=False),
    sa.Column('max_height', sa.Float(), nullable=False),
    sa.Column('max_height_relative', sa.Float(), nullable=False),
    sa.Column('flight_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('request')
    # ### end Alembic commands ###
